services:
  smartdoc-app:
    build:
      context: .
    container_name: smartdoc-app
    env_file:
      - .env
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./vector_store:/app/vector_store
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: smartdoc-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
